### ISSUE TITLE
Code String to Boolean

### ISSUE THREAD

**Issue by mayokek** [FuseMinecraft/Fuse#1]
Change `getString()` method to `getBoolean()` method - That way you can make it more neater. `true or false`

**Comment by PacksGamingHD** [comment]
Using that method will not save configuration changes when the server is reloaded or restarted. Thanks for the suggestion though

**Comment by mayokek** [comment]
It will, but you will hate doing stopping the server, editing the config and restarting the server.

**Comment by PacksGamingHD** [comment]
You're basically backing up my point of using strings instead of booleans
